
MPICC=mpicc
MPIF77=mpif77
CFLAGS+=-I/ccs/home/herault/Ref-Scalapack/scalapack-2.1.0/PBLAS/SRC/
CC=$(MPICC)
LD=mpif77

DPLASMA_DIR=/ccs/home/nlosada/dplasma_pr/install-dir/lib64
PARSEC_DIR=/ccs/home/nlosada/parsec_pr/install-dir/lib64/
DPLASMA_WRAPPER=/ccs/home/nlosada/dplasma_pr/tests/wrappers/
ESSL_DIR=/sw/summit/essl/6.1.0-2/essl/6.1/lib64/
CUDA_DIR=/sw/summit/cuda/11.0.3/lib64/
LAPACK_DIR=/ccs/home/bouteilla/parsec/dplasma/lapack/
SCALAPACK_DIR=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-5/netlib-scalapack-2.0.2-xo4jhy4ydnx3qqmnegbzfrvz4am6q2v6/lib

SLIBS=-Wl,-rpath,$(PARSEC_DIR):$(ESSL_DIR):$(CUDA_DIR) \
$(ESSL_DIR)/libessl.so $(CUDA_DIR)/libcublas.so $(CUDA_DIR)/libcudart_static.a \
/usr/lib64/libhwloc.so \
-ldl /usr/lib64/librt.so $(LAPACK_DIR)liblapacke.a \
$(LAPACK_DIR)liblapack.a \
-L$(SCALAPACK_DIR) -lscalapack \
-Wl,-rpath,$(DPLASMA_DIR) -L$(DPLASMA_DIR) -ldplasma


WLIBS=-L$(DPLASMA_WRAPPER) -Wl,-rpath,$(DPLASMA_WRAPPER) -ldplasma_scalapack $(SLIBS)

TARGETS= \
pdpotrf tpdpotrf pdpotrf_wrapped \
pdgeqrf tpdgeqrf pdgeqrf_wrapped \
pdgetrf tpdgetrf pdgetrf_wrapped \
pdgemm tpdgemm pdgemm_wrapped \
pdtrmm tpdtrmm pdtrmm_wrapped \
pdtrsm tpdtrsm pdtrsm_wrapped \
#pdsyev tpdsyev \
pdgebrd tpdgebrd \
pdpotri tpdpotrfi \


all: $(TARGETS)

common.o: common.c
	$(CC) ${CFLAGS}  -DSCALAPACK_SUP_UNDERSCORE -o $@ -c $<

p%.o: p%.c
	$(CC) ${CFLAGS}  -DSCALAPACK_SUP_UNDERSCORE -o $@ -c $<

p%: p%.o common.o
	$(LD) $(LDFLAGS) -DSCALAPACK_SUP_UNDERSCORE -o $@ $^ $(SLIBS)

#WRAPPED VERSION
common_wrapped.o: common.c
	$(CC) ${CFLAGS} -DDPLASMA_WRAPPER_ON -DSCALAPACK_SUP_UNDERSCORE -o $@ -c $<

p%_wrapped.o: p%.c
	$(CC) ${CFLAGS} -DDPLASMA_WRAPPER_ON -DSCALAPACK_SUP_UNDERSCORE -o $@ -c $<

p%_wrapped: p%_wrapped.o common_wrapped.o
	$(LD) $(LDFLAGS) -DSCALAPACK_SUP_UNDERSCORE -o $@ $^ $(WLIBS)

clean:
	$(RM) *.o $(TARGETS)
